// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Session struct {
	UserID    uuid.NullUUID
	Token     string
	CreatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Picture   sql.NullString
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
